name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libxcursor-dev libxinerama-dev
    
    - name: Create Build Repository
      run: mkdir build

    - name: Run CMake
      working-directory: ./build
      run: cmake ..

    - name: Build with Make
      working-directory: ./build
      run: cmake --build . 
