name: CMake Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache CMake build
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ runner.os }}-build-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: ${{ runner.os }}-build-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libxcursor-dev libxinerama-dev

    - name: Create Build directory
      run: mkdir -p build

    - name: Run CMake
      working-directory: ./build
      run: cmake ..

    - name: Build with CMake
      working-directory: ./build
      run: cmake --build . --parallel $(nproc)
